import { supabase } from '../lib/supabase';

export interface EmailData {
  to: string;
  subject: string;
  html: string;
  attachments?: Array<{
    filename: string;
    content: string;
    type: string;
  }>;
}

export class EmailService {
  async sendSessionReport(sessionId: string, reportUrl: string, recipientEmail: string): Promise<boolean> {
    try {
      // Get session details
      const { data: session, error } = await supabase
        .from('sessions')
        .select(`
          *,
          tutor:users!sessions_tutor_id_fkey(name),
          student:users!sessions_student_id_fkey(name)
        `)
        .eq('id', sessionId)
        .single();

      if (error || !session) {
        throw new Error('Session not found');
      }

      const emailHtml = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>Session Report - EduSync</title>
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            .header { background: linear-gradient(135deg, #00D4FF, #10B981); color: white; padding: 20px; text-align: center; }
            .content { padding: 20px; }
            .session-info { background: #f8f9fa; padding: 15px; border-radius: 8px; margin: 20px 0; }
            .metrics { display: flex; justify-content: space-around; margin: 20px 0; }
            .metric { text-align: center; padding: 15px; background: white; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
            .download-btn { background: #00D4FF; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block; margin: 20px 0; }
            .footer { background: #f8f9fa; padding: 20px; text-align: center; color: #666; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>🎓 EduSync Session Report</h1>
            <p>Detailed insights from your learning session</p>
          </div>
          
          <div class="content">
            <h2>Session Summary</h2>
            <div class="session-info">
              <p><strong>Subject:</strong> ${session.subject}</p>
              <p><strong>Student:</strong> ${session.student.name}</p>
              <p><strong>Tutor:</strong> ${session.tutor.name}</p>
              <p><strong>Date:</strong> ${new Date(session.scheduled_at).toLocaleDateString()}</p>
              <p><strong>Duration:</strong> ${session.duration_minutes} minutes</p>
            </div>

            <h3>Performance Metrics</h3>
            <div class="metrics">
              <div class="metric">
                <h4>Engagement Score</h4>
                <p style="font-size: 24px; color: #10B981; margin: 0;">${session.engagement_score || 'N/A'}%</p>
              </div>
              <div class="metric">
                <h4>Session Status</h4>
                <p style="font-size: 18px; margin: 0; text-transform: capitalize;">${session.status.replace('_', ' ')}</p>
              </div>
            </div>

            <h3>AI-Generated Insights</h3>
            <p>Our AI has analyzed this session and generated detailed insights about learning progress, engagement patterns, and recommendations for improvement.</p>

            <a href="${reportUrl}" class="download-btn">📄 Download Full Report (PDF)</a>

            <h3>Next Steps</h3>
            <ul>
              <li>Review the detailed PDF report for comprehensive insights</li>
              <li>Discuss key learning points with your tutor</li>
              <li>Schedule follow-up sessions to build on today's progress</li>
              <li>Access session recording for review (if available)</li>
            </ul>
          </div>

          <div class="footer">
            <p>This report was automatically generated by EduSync's AI-powered learning analytics.</p>
            <p>Questions? Contact us at support@edusync.com</p>
            <p style="font-size: 12px; color: #999;">© 2025 EduSync. All rights reserved.</p>
          </div>
        </body>
        </html>
      `;

      // Send email using Supabase Edge Function
      const { data, error: emailError } = await supabase.functions.invoke('send-email', {
        body: {
          to: recipientEmail,
          subject: `Session Report: ${session.subject} - ${new Date(session.scheduled_at).toLocaleDateString()}`,
          html: emailHtml,
          reportUrl: reportUrl
        }
      });

      if (emailError) {
        console.error('Email sending error:', emailError);
        return false;
      }

      // Mark report as sent
      await supabase
        .from('session_reports')
        .update({ email_sent: true })
        .eq('session_id', sessionId);

      return true;
    } catch (error) {
      console.error('Email service error:', error);
      return false;
    }
  }

  async sendWelcomeEmail(userEmail: string, userName: string, userRole: string): Promise<boolean> {
    try {
      const emailHtml = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>Welcome to EduSync</title>
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            .header { background: linear-gradient(135deg, #00D4FF, #10B981); color: white; padding: 30px; text-align: center; }
            .content { padding: 30px; }
            .feature { background: #f8f9fa; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #00D4FF; }
            .cta-btn { background: #00D4FF; color: white; padding: 15px 30px; text-decoration: none; border-radius: 6px; display: inline-block; margin: 20px 0; }
            .footer { background: #f8f9fa; padding: 20px; text-align: center; color: #666; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>🎉 Welcome to EduSync!</h1>
            <p>The future of online learning starts here</p>
          </div>
          
          <div class="content">
            <h2>Hello ${userName}!</h2>
            <p>Welcome to EduSync, the next-generation online learning platform. We're excited to have you join our community of ${userRole === 'tutor' ? 'expert educators' : 'dedicated learners'}!</p>

            <h3>What makes EduSync special?</h3>
            
            <div class="feature">
              <h4>🤖 AI-Powered Analytics</h4>
              <p>Get detailed insights into learning patterns and engagement with our advanced AI technology.</p>
            </div>

            <div class="feature">
              <h4>📹 Session Recording</h4>
              <p>Every session is automatically recorded with high-quality video and audio for later review.</p>
            </div>

            <div class="feature">
              <h4>📊 Real-time Insights</h4>
              <p>Track progress with live engagement metrics and comprehensive performance reports.</p>
            </div>

            <div class="feature">
              <h4>📧 Automated Reports</h4>
              <p>Detailed PDF reports are automatically generated and sent after each session.</p>
            </div>

            ${userRole === 'tutor' ? `
              <h3>Getting Started as a Tutor</h3>
              <ul>
                <li>Complete your professional profile with certifications and subjects</li>
                <li>Add students to your teaching roster</li>
                <li>Schedule and conduct your first recorded session</li>
                <li>Review AI-generated insights about student engagement</li>
              </ul>
            ` : `
              <h3>Getting Started as a ${userRole === 'parent' ? 'Parent' : 'Student'}</h3>
              <ul>
                <li>Browse and connect with expert tutors</li>
                <li>Schedule your first learning session</li>
                <li>Experience AI-powered session recording</li>
                <li>Receive detailed progress reports after each session</li>
              </ul>
            `}

            <a href="${window.location.origin}/auth" class="cta-btn">🚀 Start Your Learning Journey</a>

            <h3>Need Help?</h3>
            <p>Our support team is here to help you get the most out of EduSync:</p>
            <ul>
              <li>📧 Email: support@edusync.com</li>
              <li>💬 Live Chat: Available 24/7 in your dashboard</li>
              <li>📚 Help Center: Comprehensive guides and tutorials</li>
            </ul>
          </div>

          <div class="footer">
            <p>Thank you for choosing EduSync for your educational journey!</p>
            <p style="font-size: 12px; color: #999;">© 2025 EduSync. All rights reserved.</p>
          </div>
        </body>
        </html>
      `;

      const { error } = await supabase.functions.invoke('send-email', {
        body: {
          to: userEmail,
          subject: 'Welcome to EduSync - Your Learning Journey Begins!',
          html: emailHtml
        }
      });

      return !error;
    } catch (error) {
      console.error('Welcome email error:', error);
      return false;
    }
  }
}